language: rust
sudo: false

rust:
  # We require nightly for conservative_impl_trait, unboxed_closures and fn_traits
  - nightly

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- $FEATURES &&
      travis-cargo test -- $FEATURES &&
      travis-cargo bench -- $FEATURES &&
      travis-cargo --only stable doc

after_success:
  - |
    [ $TRAVIS_BRANCH = master ] &&
    [ -z "$FEATURES" ] &&
    travis-cargo --only stable doc-upload
  - travis-cargo --only nightly coveralls --no-sudo

env:
  matrix:
    - FEATURES="--features noop_error"
    - FEATURES="--features backtrace"
    - FEATURES="--features tendril"
    # Travis seems to have issues with quotation in env-vars, use a merged feature
    - FEATURES="--features noop_error_and_backtrace"
    - FEATURES=""
  global:
    - secure: gsvH3282enp+tO7Hjd0BEUnv9+jX0uQ/E9+B07ZPcbjYvoSA68Hk2UfZb1IYMWWXO1mWR8zF1Q/AnZR26fYEtlGaF8vTRqoYQHCc5pYUxNaSJPf1C2fvGpiRW63h9lC9sAwia7r2oS+aBeXHdrxvPtScMescf+fzjdeTYy4sHAg9ahrMIDlXB2cFXBixyqbjKwPB3wT0VqjOc8avzhAKehxXU8/h51P2FjRXLv/aEs/cMV7vpGGAZG4uA9cgrql7zayWMdiUNFGzR0Di7r3tDK3TPsla1c1W5+YYrbWkXT/cX5AvpDa9IH+jookPITzNlN7v6ZAQiwBzE7U2qzbZu34QAk34lfEwlcF/wVfuiKfUwR/U+B8Lb5tFPBF1lWn/NOw+uec4d/0XO2K6sfVxXn0nMrfeA/L8Q3pJ+3Fmts+gP4oumrjZ9L+zoYE+Lpn22T2W81BOPuW2c1JvbB5ZDds4ztHc2BL4aiYSO9DzMYTCz4sT/UbDbgVWkhwwfeKarCAvTmfTfpgIsNdnMdkiMX4gLIzm1W0xwtTc8Tl7GgCQjO8zxcgZT67bi507Huf9zQ4AwaBN4P9jCGSsa+bleIcUeR5NkX2KJlT5WNqUIyCHqHwG18Ddm8jmSMut4AVsyXkdAONq4Xfa07cZUBoKtAahrgl8UqXclCjtw31acGk=
